{
 "title": "Weather Events",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "daily hottest city",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH daily_max_temp AS (\n    SELECT\n        date(date_time) AS day,\n        city,\n        apparent_temperature,\n        RANK() OVER (PARTITION BY date(date_time) ORDER BY apparent_temperature DESC) as temp_rank\n    FROM weather_event \n)\nSELECT TO_CHAR(day,'YYYY-MM-DD') as day, city, apparent_temperature\nFROM daily_max_temp\nWHERE temp_rank = 1\nORDER BY day ASC;\n"
    }
   ]
  },
  {
   "title": "daily coldest cities",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH daily_min_temp AS (\n    SELECT\n        date(date_time) AS day,\n        city,\n        apparent_temperature,\n        RANK() OVER (PARTITION BY date(date_time) ORDER BY apparent_temperature) as temp_rank\n    FROM weather_event \n)\nSELECT TO_CHAR(day,'YYYY-MM-DD') as day, city, apparent_temperature\nFROM daily_min_temp\nWHERE temp_rank = 1\nORDER BY day ASC;"
    }
   ]
  },
  {
   "title": "Monthly hottest cities ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH monthly_max_temp AS (\n    SELECT\n        date_trunc('month', date_time) AS month,\n        city,\n        apparent_temperature,\n        RANK() OVER (PARTITION BY date_trunc('month', date_time) ORDER BY apparent_temperature DESC) as temp_rank\n    FROM weather_event \n)\nSELECT TO_CHAR(month,'YYYY-MM') as month, city, apparent_temperature\nFROM monthly_max_temp\nWHERE temp_rank = 1\nORDER BY month ASC;"
    }
   ]
  },
  {
   "title": "Monthly coldest cities ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH monthly_min_temp AS (\n    SELECT\n        date_trunc('month', date_time) AS month,\n        city,\n        apparent_temperature,\n        RANK() OVER (PARTITION BY date_trunc('month', date_time) ORDER BY apparent_temperature) as temp_rank\n    FROM weather_event \n)\nSELECT TO_CHAR(month,'YYYY-MM') as month, city, apparent_temperature\nFROM monthly_min_temp\nWHERE temp_rank = 1\nORDER BY month ASC;"
    }
   ]
  },
  {
   "title": "Most humid city in each day",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "WITH daily_humidity AS (\n  SELECT\n    DATE(date_time) AS date,\n    city,\n    AVG(humidity) AS avg_humidity\n  FROM weather_event\n  GROUP BY date, city\n),\nranked_cities AS (\n  SELECT\n    date,\n    city,\n    avg_humidity,\n    RANK() OVER (PARTITION BY date ORDER BY avg_humidity DESC) as humidity_rank\n  FROM daily_humidity\n)\nSELECT TO_CHAR(date, 'YYYY-MM-DD') AS day, city, avg_humidity\nFROM ranked_cities\nWHERE humidity_rank = 1;"
    }
   ]
  }
 ]
}